apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-persistent-storage
  namespace: development
  labels:
    app: mongo-db
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
